all: Project1

Project1: Main.cpp GameWorld.cpp Dungeon.cpp Room.cpp CombatUnit.cpp Player.cpp Enemy.cpp Item.cpp BitCoin.cpp Bulbasaur.cpp Chest.cpp Chinchilla.cpp ClumsyRobot.cpp Cute.cpp HamSandwich.cpp HealthPotion.cpp LargeRock.cpp ManaPotion.cpp MasterBall.cpp MasterBallCapture.cpp Mimic.cpp NAO.cpp Robot.cpp RobotArm.cpp Troll.cpp	
	g++ Main.cpp GameWorld.cpp Dungeon.cpp Room.cpp CombatUnit.cpp Player.cpp Enemy.cpp Item.cpp BitCoin.cpp Bulbasaur.cpp Chest.cpp Chinchilla.cpp ClumsyRobot.cpp Cute.cpp HamSandwich.cpp HealthPotion.cpp LargeRock.cpp ManaPotion.cpp MasterBall.cpp MasterBallCapture.cpp Mimic.cpp NAO.cpp Robot.cpp RobotArm.cpp Troll.cpp  -std=c++11 -o Adventure
	
