all: Project1

Project1: Main.cpp GameWorld.cpp Dungeon.cpp Room.cpp CombatUnit.cpp Player.cpp Enemy.cpp Item.cpp Mimic.cpp
	g++ Main.cpp GameWorld.cpp Dungeon.cpp Room.cpp CombatUnit.cpp Player.cpp Enemy.cpp Item.cpp Mimic.cpp -std=c++11 -o Adventure
	
